// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/generate_shader_register_map.cmake

#ifndef XYLEM_SHADER_REGISTER_MAP_H
#define XYLEM_SHADER_REGISTER_MAP_H

#include <cstdint>

namespace Xylem::shader::reg {

namespace Compute {
namespace Cull {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kSRV_HiZ = 4;
inline constexpr uint32_t kSRV_ImpostorSlotOffsets = 5;
inline constexpr uint32_t kSRV_InstanceData = 1;
inline constexpr uint32_t kSRV_MainSlotOffsets = 2;
inline constexpr uint32_t kSRV_RegionData = 0;
inline constexpr uint32_t kSRV_ShadowImpostorSlotOffsets = 6;
inline constexpr uint32_t kSRV_ShadowSlotOffsets = 3;
inline constexpr uint32_t kUAV_ImpostorCount = 8;
inline constexpr uint32_t kUAV_ImpostorIndirectArgs = 10;
inline constexpr uint32_t kUAV_ImpostorVis = 9;
inline constexpr uint32_t kUAV_LeafMainIndirectArgs = 14;
inline constexpr uint32_t kUAV_LeafShadowIndirectArgs = 15;
inline constexpr uint32_t kUAV_MainIndirectArgs = 5;
inline constexpr uint32_t kUAV_MainRegionVis = 0;
inline constexpr uint32_t kUAV_MainSlotCount = 1;
inline constexpr uint32_t kUAV_MainVis = 2;
inline constexpr uint32_t kUAV_ShadowImpostorCount = 11;
inline constexpr uint32_t kUAV_ShadowImpostorIndirectArgs = 13;
inline constexpr uint32_t kUAV_ShadowImpostorVis = 12;
inline constexpr uint32_t kUAV_ShadowIndirectArgs = 6;
inline constexpr uint32_t kUAV_ShadowSlotCount = 3;
inline constexpr uint32_t kUAV_ShadowUniqueCounter = 7;
inline constexpr uint32_t kUAV_ShadowVis = 4;
} // namespace Cull

namespace DepthPrepass {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kPushC_Slot = 1;
inline constexpr uint32_t kSRV_Instances = 1;
inline constexpr uint32_t kSRV_SlotOffsets = 2;
inline constexpr uint32_t kSRV_Vis = 0;
} // namespace DepthPrepass

namespace HiZ {
inline constexpr uint32_t kPushC_DestDimensions = 0;
inline constexpr uint32_t kSRV_Source = 0;
inline constexpr uint32_t kUAV_Dest = 0;
} // namespace HiZ

namespace ImpostorBake {
inline constexpr uint32_t kCB_Bake = 0;
inline constexpr uint32_t kPushC_LeafIdx = 1;
inline constexpr uint32_t kSRV_BakeLeaves = 0;
inline constexpr uint32_t kSampler_Main = 0;
inline constexpr uint32_t kTex_Diffuse = 0;
inline constexpr uint32_t kTex_NormalMap = 1;
} // namespace ImpostorBake

namespace Impostor {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kPushC_AssetIndex = 1;
inline constexpr uint32_t kSRV_AssetDims = 8;
inline constexpr uint32_t kSRV_CullData = 3;
inline constexpr uint32_t kSRV_Instances = 1;
inline constexpr uint32_t kSRV_SlotOffsets = 2;
inline constexpr uint32_t kSRV_Vis = 0;
inline constexpr uint32_t kSampler_Depth = 2;
inline constexpr uint32_t kSampler_Main = 0;
inline constexpr uint32_t kSampler_Shadow = 1;
inline constexpr uint32_t kTex_Albedo = 4;
inline constexpr uint32_t kTex_Depth = 6;
inline constexpr uint32_t kTex_Normal = 5;
inline constexpr uint32_t kTex_ShadowMap = 7;
} // namespace Impostor

namespace Leaf {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kPushC_Slot = 1;
inline constexpr uint32_t kSRV_Instances = 1;
inline constexpr uint32_t kSRV_LeafInstances = 3;
inline constexpr uint32_t kSRV_LeafSlots = 4;
inline constexpr uint32_t kSRV_SlotOffsets = 2;
inline constexpr uint32_t kSRV_Vis = 0;
inline constexpr uint32_t kSampler_Shadow = 0;
inline constexpr uint32_t kTex_ShadowMap = 5;
} // namespace Leaf

namespace SDSM {
inline constexpr uint32_t kCB_Input = 0;
inline constexpr uint32_t kSRV_HiZ = 0;
inline constexpr uint32_t kUAV_CascadeOut = 0;
} // namespace SDSM

namespace Scene {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kPushC_Slot = 1;
inline constexpr uint32_t kSRV_Instances = 1;
inline constexpr uint32_t kSRV_SlotOffsets = 2;
inline constexpr uint32_t kSRV_Vis = 0;
inline constexpr uint32_t kSampler_Main = 0;
inline constexpr uint32_t kSampler_Shadow = 1;
inline constexpr uint32_t kTex_Diffuse = 3;
inline constexpr uint32_t kTex_NormalMap = 4;
inline constexpr uint32_t kTex_ShadowMap = 5;
} // namespace Scene

namespace ShadowImpostor {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kPushC_AssetCascade = 1;
inline constexpr uint32_t kSRV_AssetDims = 6;
inline constexpr uint32_t kSRV_CullData = 3;
inline constexpr uint32_t kSRV_Instances = 1;
inline constexpr uint32_t kSRV_SlotOffsets = 2;
inline constexpr uint32_t kSRV_Vis = 0;
inline constexpr uint32_t kSampler_Depth = 1;
inline constexpr uint32_t kSampler_Main = 0;
inline constexpr uint32_t kTex_Albedo = 4;
inline constexpr uint32_t kTex_Depth = 5;
} // namespace ShadowImpostor

namespace Shadow {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kPushC_AssetCascade = 1;
inline constexpr uint32_t kSRV_Instances = 1;
inline constexpr uint32_t kSRV_SlotOffsets = 2;
inline constexpr uint32_t kSRV_Vis = 0;
} // namespace Shadow

namespace Sky {
inline constexpr uint32_t kCB_Sky = 0;
} // namespace Sky

namespace Terrain {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kCB_Shading = 1;
inline constexpr uint32_t kSampler_Aniso = 1;
inline constexpr uint32_t kSampler_Shadow = 0;
inline constexpr uint32_t kTex_DirtDiff = 3;
inline constexpr uint32_t kTex_DirtNor = 4;
inline constexpr uint32_t kTex_ForestDiff = 1;
inline constexpr uint32_t kTex_ForestNor = 2;
inline constexpr uint32_t kTex_RockDiff = 5;
inline constexpr uint32_t kTex_RockNor = 6;
inline constexpr uint32_t kTex_ShadowMap = 0;
inline constexpr uint32_t kTex_SnowDiff = 7;
inline constexpr uint32_t kTex_SnowNor = 8;
} // namespace Terrain

} // namespace Compute

namespace Mesh {
namespace Cull {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kSRV_HiZ = 6;
inline constexpr uint32_t kSRV_ImpostorSlotOffsets = 7;
inline constexpr uint32_t kSRV_InstanceData = 1;
inline constexpr uint32_t kSRV_MainInvocations = 3;
inline constexpr uint32_t kSRV_MainLeafInvocations = 8;
inline constexpr uint32_t kSRV_MainSlotOffsets = 2;
inline constexpr uint32_t kSRV_RegionData = 0;
inline constexpr uint32_t kSRV_ShadowImpostorSlotOffsets = 10;
inline constexpr uint32_t kSRV_ShadowInvocations = 5;
inline constexpr uint32_t kSRV_ShadowLeafInvocations = 9;
inline constexpr uint32_t kSRV_ShadowSlotOffsets = 4;
inline constexpr uint32_t kUAV_ImpostorCount = 8;
inline constexpr uint32_t kUAV_ImpostorIndirectArgs = 10;
inline constexpr uint32_t kUAV_ImpostorVis = 9;
inline constexpr uint32_t kUAV_MainCount = 1;
inline constexpr uint32_t kUAV_MainDispatch = 3;
inline constexpr uint32_t kUAV_MainLeafDispatch = 11;
inline constexpr uint32_t kUAV_MainRegionVis = 0;
inline constexpr uint32_t kUAV_MainVis = 2;
inline constexpr uint32_t kUAV_ShadowCount = 4;
inline constexpr uint32_t kUAV_ShadowDispatch = 6;
inline constexpr uint32_t kUAV_ShadowImpostorCount = 13;
inline constexpr uint32_t kUAV_ShadowImpostorIndirectArgs = 15;
inline constexpr uint32_t kUAV_ShadowImpostorVis = 14;
inline constexpr uint32_t kUAV_ShadowLeafDispatch = 12;
inline constexpr uint32_t kUAV_ShadowUnique = 7;
inline constexpr uint32_t kUAV_ShadowVis = 5;
} // namespace Cull

namespace DepthPrepass {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kPushC_Slot = 1;
inline constexpr uint32_t kSRV_Instances = 1;
inline constexpr uint32_t kSRV_SlotOffsets = 2;
inline constexpr uint32_t kSRV_Vis = 0;
} // namespace DepthPrepass

namespace Draw {
inline constexpr uint32_t kCB_ASCull = 2;
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kPushC_Slot = 1;
inline constexpr uint32_t kSRV_ASInvocations = 13;
inline constexpr uint32_t kSRV_AssetLods = 8;
inline constexpr uint32_t kSRV_Bitangents = 3;
inline constexpr uint32_t kSRV_Instances = 12;
inline constexpr uint32_t kSRV_MeshletPrimIdx = 6;
inline constexpr uint32_t kSRV_MeshletVertIdx = 5;
inline constexpr uint32_t kSRV_Meshlets = 7;
inline constexpr uint32_t kSRV_Normals = 1;
inline constexpr uint32_t kSRV_Positions = 0;
inline constexpr uint32_t kSRV_SlotCounts = 11;
inline constexpr uint32_t kSRV_SlotOffsets = 10;
inline constexpr uint32_t kSRV_Tangents = 2;
inline constexpr uint32_t kSRV_UVs = 4;
inline constexpr uint32_t kSRV_Vis = 9;
inline constexpr uint32_t kSampler_Main = 0;
inline constexpr uint32_t kSampler_Shadow = 1;
inline constexpr uint32_t kTex_Diffuse = 14;
inline constexpr uint32_t kTex_HiZ = 17;
inline constexpr uint32_t kTex_NormalMap = 15;
inline constexpr uint32_t kTex_ShadowMap = 16;
inline constexpr uint32_t kUAV_MeshletStats = 0;
} // namespace Draw

namespace HiZ {
inline constexpr uint32_t kPushC_DestDimensions = 0;
inline constexpr uint32_t kSRV_Source = 0;
inline constexpr uint32_t kUAV_Dest = 0;
} // namespace HiZ

namespace Leaf {
inline constexpr uint32_t kCB_ASCull = 2;
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kPushC_Slot = 1;
inline constexpr uint32_t kSRV_ASInvocations = 4;
inline constexpr uint32_t kSRV_Instances = 3;
inline constexpr uint32_t kSRV_LeafInstances = 5;
inline constexpr uint32_t kSRV_LeafMeshlets = 7;
inline constexpr uint32_t kSRV_LeafSlots = 6;
inline constexpr uint32_t kSRV_SlotCounts = 2;
inline constexpr uint32_t kSRV_SlotOffsets = 1;
inline constexpr uint32_t kSRV_Vis = 0;
inline constexpr uint32_t kSampler_Shadow = 0;
inline constexpr uint32_t kTex_HiZ = 9;
inline constexpr uint32_t kTex_ShadowMap = 8;
inline constexpr uint32_t kUAV_LeafSurvivor = 0;
inline constexpr uint32_t kUAV_MeshletStats = 1;
} // namespace Leaf

namespace SDSM {
inline constexpr uint32_t kCB_Input = 0;
inline constexpr uint32_t kSRV_HiZ = 0;
inline constexpr uint32_t kUAV_CascadeOut = 0;
} // namespace SDSM

namespace Sky {
inline constexpr uint32_t kCB_Sky = 0;
} // namespace Sky

namespace Terrain {
inline constexpr uint32_t kCB_ASCull = 2;
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kCB_Shading = 1;
inline constexpr uint32_t kPushC_Cascade = 3;
inline constexpr uint32_t kSRV_MeshletDescs = 10;
inline constexpr uint32_t kSRV_MeshletPrimIdx = 12;
inline constexpr uint32_t kSRV_MeshletVertIdx = 11;
inline constexpr uint32_t kSRV_Normals = 14;
inline constexpr uint32_t kSRV_Positions = 9;
inline constexpr uint32_t kSRV_UVs = 15;
inline constexpr uint32_t kSampler_Aniso = 1;
inline constexpr uint32_t kSampler_Shadow = 0;
inline constexpr uint32_t kTex_DirtDiff = 3;
inline constexpr uint32_t kTex_DirtNor = 4;
inline constexpr uint32_t kTex_ForestDiff = 1;
inline constexpr uint32_t kTex_ForestNor = 2;
inline constexpr uint32_t kTex_HiZ = 13;
inline constexpr uint32_t kTex_RockDiff = 5;
inline constexpr uint32_t kTex_RockNor = 6;
inline constexpr uint32_t kTex_ShadowMap = 0;
inline constexpr uint32_t kTex_SnowDiff = 7;
inline constexpr uint32_t kTex_SnowNor = 8;
inline constexpr uint32_t kUAV_VisibleCounter = 0;
} // namespace Terrain

} // namespace Mesh

namespace Traditional {
namespace Leaf {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kPushC_Slot = 1;
inline constexpr uint32_t kSRV_LeafInstances = 0;
inline constexpr uint32_t kSRV_LeafSlots = 1;
inline constexpr uint32_t kSampler_Shadow = 0;
inline constexpr uint32_t kTex_ShadowMap = 2;
} // namespace Leaf

namespace Shadow {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kPushC_CascadeIndex = 1;
} // namespace Shadow

namespace Sky {
inline constexpr uint32_t kCB_Sky = 0;
} // namespace Sky

namespace Terrain {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kCB_Shading = 1;
inline constexpr uint32_t kSampler_Aniso = 1;
inline constexpr uint32_t kSampler_Shadow = 0;
inline constexpr uint32_t kTex_DirtDiff = 3;
inline constexpr uint32_t kTex_DirtNor = 4;
inline constexpr uint32_t kTex_ForestDiff = 1;
inline constexpr uint32_t kTex_ForestNor = 2;
inline constexpr uint32_t kTex_RockDiff = 5;
inline constexpr uint32_t kTex_RockNor = 6;
inline constexpr uint32_t kTex_ShadowMap = 0;
inline constexpr uint32_t kTex_SnowDiff = 7;
inline constexpr uint32_t kTex_SnowNor = 8;
} // namespace Terrain

namespace Tree {
inline constexpr uint32_t kCB_Frame = 0;
inline constexpr uint32_t kSampler_Main = 0;
inline constexpr uint32_t kSampler_Shadow = 1;
inline constexpr uint32_t kTex_Diffuse = 0;
inline constexpr uint32_t kTex_NormalMap = 1;
inline constexpr uint32_t kTex_ShadowMap = 2;
} // namespace Tree

} // namespace Traditional

} // namespace Xylem::shader::reg

#endif // XYLEM_SHADER_REGISTER_MAP_H

