cmake_minimum_required(VERSION 3.31)

foreach(_required_var IN ITEMS SHADER_REG_SPEC SHADER_REG_CPP SHADER_REG_HLSL)
    if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
        message(FATAL_ERROR "Missing required -D${_required_var}=... argument.")
    endif()
endforeach()

function(_shader_reg_to_macro_token _out_var _name)
    set(_token "${_name}")
    string(REGEX REPLACE "^k" "" _token "${_token}")
    string(REGEX REPLACE "([a-z0-9])([A-Z])" "\\1_\\2" _token "${_token}")
    while(_token MATCHES "__")
        string(REPLACE "__" "_" _token "${_token}")
    endwhile()
    string(TOUPPER "${_token}" _token)
    set(${_out_var} "${_token}" PARENT_SCOPE)
endfunction()

file(READ "${SHADER_REG_SPEC}" _spec_json)
string(JSON _register_count LENGTH "${_spec_json}" registers)

set(_valid_kinds b t u s)
set(_entries)
set(_seen_cpp_symbols)
set(_seen_macros)

if(_register_count GREATER 0)
    math(EXPR _register_last "${_register_count} - 1")
    foreach(_idx RANGE 0 ${_register_last})
        string(JSON _ns_len LENGTH "${_spec_json}" registers ${_idx} namespace)
        if(_ns_len LESS 1)
            message(FATAL_ERROR "registers[${_idx}] has empty namespace.")
        endif()

        set(_ns_parts)
        set(_ns_token_parts)
        math(EXPR _ns_last "${_ns_len} - 1")
        foreach(_ns_idx RANGE 0 ${_ns_last})
            string(JSON _ns_part GET "${_spec_json}" registers ${_idx} namespace ${_ns_idx})
            if(_ns_part STREQUAL "")
                message(FATAL_ERROR "registers[${_idx}] has empty namespace component.")
            endif()
            list(APPEND _ns_parts "${_ns_part}")
            string(TOUPPER "${_ns_part}" _ns_upper)
            list(APPEND _ns_token_parts "${_ns_upper}")
        endforeach()

        string(JSON _name GET "${_spec_json}" registers ${_idx} name)
        if(NOT _name MATCHES "^k[A-Za-z0-9_]*$")
            message(FATAL_ERROR "registers[${_idx}] has invalid name '${_name}'.")
        endif()

        string(JSON _kind GET "${_spec_json}" registers ${_idx} kind)
        list(FIND _valid_kinds "${_kind}" _kind_index)
        if(_kind_index EQUAL -1)
            message(FATAL_ERROR "registers[${_idx}] has invalid kind '${_kind}'.")
        endif()

        string(JSON _slot GET "${_spec_json}" registers ${_idx} slot)
        if(NOT _slot MATCHES "^[0-9]+$")
            message(FATAL_ERROR "registers[${_idx}] has invalid slot '${_slot}'.")
        endif()

        list(JOIN _ns_parts "/" _ns_path)
        list(JOIN _ns_parts "::" _ns_cpp)
        list(JOIN _ns_token_parts "_" _ns_token)

        set(_cpp_symbol "${_ns_cpp}::${_name}")
        list(FIND _seen_cpp_symbols "${_cpp_symbol}" _existing_cpp_symbol_index)
        if(NOT _existing_cpp_symbol_index EQUAL -1)
            message(FATAL_ERROR "Duplicate C++ symbol '${_cpp_symbol}'.")
        endif()
        list(APPEND _seen_cpp_symbols "${_cpp_symbol}")

        _shader_reg_to_macro_token(_sym_token "${_name}")
        string(TOUPPER "${_kind}" _kind_upper)
        set(_macro "XY_REG_${_kind_upper}_${_ns_token}_${_sym_token}")
        list(FIND _seen_macros "${_macro}" _existing_macro_index)
        if(NOT _existing_macro_index EQUAL -1)
            message(FATAL_ERROR "Duplicate HLSL macro '${_macro}'.")
        endif()
        list(APPEND _seen_macros "${_macro}")

        list(APPEND _entries "${_ns_path}|${_name}|${_kind}|${_slot}|${_macro}")
    endforeach()
endif()

list(SORT _entries)

set(_cpp_lines
    "// AUTO-GENERATED FILE. DO NOT EDIT."
    "// Generated by tools/generate_shader_register_map.cmake"
    ""
    "#ifndef XYLEM_SHADER_REGISTER_MAP_H"
    "#define XYLEM_SHADER_REGISTER_MAP_H"
    ""
    "#include <cstdint>"
    ""
    "namespace Xylem::shader::reg {"
    ""
)

set(_prev_ns_parts)
foreach(_entry IN LISTS _entries)
    string(REPLACE "|" ";" _fields "${_entry}")
    list(GET _fields 0 _ns_path)
    list(GET _fields 1 _name)
    list(GET _fields 3 _slot)

    string(REPLACE "/" ";" _ns_parts "${_ns_path}")

    list(LENGTH _prev_ns_parts _prev_len)
    list(LENGTH _ns_parts _ns_len)
    set(_common_len 0)
    while(_common_len LESS _prev_len AND _common_len LESS _ns_len)
        list(GET _prev_ns_parts ${_common_len} _prev_part)
        list(GET _ns_parts ${_common_len} _current_part)
        if(NOT _prev_part STREQUAL _current_part)
            break()
        endif()
        math(EXPR _common_len "${_common_len} + 1")
    endwhile()

    if(_prev_len GREATER _common_len)
        math(EXPR _close_idx "${_prev_len} - 1")
        while(_close_idx GREATER_EQUAL _common_len)
            list(GET _prev_ns_parts ${_close_idx} _closing_ns)
            list(APPEND _cpp_lines "} // namespace ${_closing_ns}")
            list(APPEND _cpp_lines "")
            math(EXPR _close_idx "${_close_idx} - 1")
        endwhile()
    endif()

    if(_ns_len GREATER _common_len)
        math(EXPR _open_last "${_ns_len} - 1")
        foreach(_open_idx RANGE ${_common_len} ${_open_last})
            list(GET _ns_parts ${_open_idx} _opening_ns)
            list(APPEND _cpp_lines "namespace ${_opening_ns} {")
        endforeach()
    endif()

    # Keep a placeholder here because ';' is a CMake list delimiter.
    list(APPEND _cpp_lines "inline constexpr uint32_t ${_name} = ${_slot}__SC__")
    set(_prev_ns_parts ${_ns_parts})
endforeach()

list(LENGTH _prev_ns_parts _remaining_ns_count)
if(_remaining_ns_count GREATER 0)
    math(EXPR _close_idx "${_remaining_ns_count} - 1")
    while(_close_idx GREATER_EQUAL 0)
        list(GET _prev_ns_parts ${_close_idx} _closing_ns)
        list(APPEND _cpp_lines "} // namespace ${_closing_ns}")
        list(APPEND _cpp_lines "")
        math(EXPR _close_idx "${_close_idx} - 1")
    endwhile()
endif()

list(APPEND _cpp_lines
    "} // namespace Xylem::shader::reg"
    ""
    "#endif // XYLEM_SHADER_REGISTER_MAP_H"
    ""
)

set(_hlsl_lines
    "// AUTO-GENERATED FILE. DO NOT EDIT."
    "// Generated by tools/generate_shader_register_map.cmake"
    ""
    "#ifndef XYLEM_SHADER_REGISTER_MAP_HLSLI"
    "#define XYLEM_SHADER_REGISTER_MAP_HLSLI"
    ""
)

foreach(_entry IN LISTS _entries)
    string(REPLACE "|" ";" _fields "${_entry}")
    list(GET _fields 2 _kind)
    list(GET _fields 3 _slot)
    list(GET _fields 4 _macro)
    list(APPEND _hlsl_lines "#define ${_macro} ${_kind}${_slot}")
endforeach()

list(APPEND _hlsl_lines
    ""
    "#endif // XYLEM_SHADER_REGISTER_MAP_HLSLI"
    ""
)

get_filename_component(_cpp_dir "${SHADER_REG_CPP}" DIRECTORY)
get_filename_component(_hlsl_dir "${SHADER_REG_HLSL}" DIRECTORY)
file(MAKE_DIRECTORY "${_cpp_dir}" "${_hlsl_dir}")

list(JOIN _cpp_lines "\n" _cpp_content)
string(REPLACE "__SC__" ";" _cpp_content "${_cpp_content}")
list(JOIN _hlsl_lines "\n" _hlsl_content)
file(WRITE "${SHADER_REG_CPP}" "${_cpp_content}\n")
file(WRITE "${SHADER_REG_HLSL}" "${_hlsl_content}\n")
