#ifndef PIPELINER_MACROS_H
#define PIPELINER_MACROS_H

#define PIPELINER_USE_INTERLEAVED_VERTEX_ATTRIBUTES 1
#define PIPELINER_USE_STRUCTURED_BUFFER             0
#define PIPELINER_USE_REVERSE_Z                     1

#endif